name: TdBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@master
      - run:  bash waho.sh
      - uses: actions/upload-artifact@master
        with:
         name: tdjson
         path: /root/out
