name: TdDock
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@master
      - run:  bash waho.sh
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name:  accipiter7/tdwaho
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: --force-rm --compress --no-cache --squash
          tags: "latest"
